spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/server
    username: ramu
    password: ramu
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  # Hibernate ddl auto (create, create-drop, validate, update)



#spring:
#  datasource:
#    password: root
#    url: jdbc:mysql://localhost:3306/server_db
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#    show-sql: true
